### ISSUE TITLE
Enhance player controls to "Pull" objects

### ISSUE THREAD

**Issue by pboyer84** [Inn0cu0us/Teddy#2]
When the player is next to a ritual object and presses "Push", the player should be able to walk away from the object and pull it. If the object collides with something along the way, the pull should be broken.

It may appropriate to rename the Push action in the context of this issue, since the same button is for pushing and pulling objects..

**Comment by exenteth** [comment]
A "pull" feature is difficult to implement when the character never faces any directions! (in which direction should we be checking for objects?)

**Comment by exenteth** [comment]
Pull is now implemented, press "push" button in front of object to link it to character, object will be released when buttons is released. Uses last known movement vector to decide which object to grab. Fixed Use button in the same way.
